name: esp32h2

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - '!src/platforms/arm/**'
      - '!src/platforms/wasm/**'
      - '!src/platforms/avr/**'
      - 'src/platforms/esp/**'
      - 'examples/**'
      - 'ci/**'
      - '.github/workflows/build_esp32h2.yml'
      - '.github/workflows/build_template.yml'
      - 'CMakeLists.txt'
      - 'platformio.ini'
      - 'library.json'
      - 'library.properties'
  pull_request_target:
    branches:
      - master
    paths:
      - 'src/**'
      - '!src/platforms/arm/**'
      - '!src/platforms/wasm/**'
      - '!src/platforms/avr/**'
      - 'src/platforms/esp/**'
      - 'examples/**'
      - 'ci/**'
      - '.github/workflows/build_esp32h2.yml'
      - '.github/workflows/build_template.yml'
      - 'CMakeLists.txt'
      - 'platformio.ini'
      - 'library.json'
      - 'library.properties'

jobs:
  build:
    uses: ./.github/workflows/build_template.yml
    with:
      args: esp32h2
